# SPDX-FileCopyrightText: Florian Maurer
#
# SPDX-License-Identifier: AGPL-3.0-or-later

default:
  tags:
    - shared

stages:
- build
- deploy

build-docker:
  image: docker:dind
  services:
    - docker:dind
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -f Dockerfile_dwd  -t "$CI_REGISTRY_IMAGE/dwd_crawler:latest" .
    - docker push $CI_REGISTRY_IMAGE/dwd_crawler:latest
