# SPDX-FileCopyrightText: Florian Maurer
#
# SPDX-License-Identifier: AGPL-3.0-or-later

db_uri: "postgresql://opendata:opendata@localhost:6432/opendata?options=--search_path={DBNAME}"
# for local sqlite database
# db_uri: "sqlite:///{DBNAME}.db"
entsoe_api_key: "YOUR_ENTSOE_API_KEY"
regelleistung_api_key: "YOUR_REGELLEISTUNG_API_KEY"
gie_api_key: "YOUR_GIE_API_KEY"
ipnt_client_id: "YOUR_IPNT_CLIENT_ID"
ipnt_client_secret: "YOUR_IPNT_CLIENT_SECRET"
